## name: gruvbox light knight
## blurb: warm parchment light theme

foreground                      #333231
background                      #f1e4bb
selection_foreground            #f1e4bb
selection_background            #514f49

cursor                          #333231
cursor_text_color               #f1e4bb
url_color                       #6f6959

active_border_color             #6f6959
inactive_border_color           #ded1ac
bell_border_color               #847b66
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_foreground           #f1e4bb
active_tab_background           #514f49
inactive_tab_foreground         #6f6959
inactive_tab_background         #ded1ac
tab_bar_background              none
tab_bar_margin_color            none

mark1_foreground #f1e4bb
mark1_background #6f6959
mark2_foreground #f1e4bb
mark2_background #514f49
mark3_foreground #f1e4bb
mark3_background #847b66

color0  #f1e4bb
color8  #b7ac8e
color1  #847b66
color9  #6f6959
color2  #6b695d
color10 #514f49
color3  #958b73
color11 #333231
color4  #ded1ac
color12 #d4c894
color5  #847b66
color13 #6f6959
color6  #6b695d
color14 #514f49
color7  #43413d
color15 #333231
