## name: gruvbox
## blurb: warm retro dark with earthy greens and muted teal

foreground                      #d4be98
background                      #282828
selection_foreground            #ebdbb2
selection_background            #d65d0e

cursor                          #bdae93
cursor_text_color               #282828
url_color                       #89b482

active_border_color             #7daea3
inactive_border_color           #3c3836
bell_border_color               #ea6962

active_tab_foreground           #282828
active_tab_background           #7daea3
inactive_tab_foreground         #665c54
inactive_tab_background         #3c3836
tab_bar_background              #282828

color0                          #3c3836
color8                          #3c3836
color1                          #ea6962
color9                          #ea6962
color2                          #a9b665
color10                         #a9b665
color3                          #d8a657
color11                         #d8a657
color4                          #7daea3
color12                         #7daea3
color5                          #d3869b
color13                         #d3869b
color6                          #89b482
color14                         #89b482
color7                          #d4be98
color15                         #d4be98
