## name: retro-82
## blurb: deep navy midnight with warm amber and retro teal

foreground                      #f6dcac
background                      #05182e
selection_foreground            #00172e
selection_background            #faa968

cursor                          #f6dcac
cursor_text_color               #05182e
url_color                       #8cbfb8

active_border_color             #faa968
inactive_border_color           #134e5a
bell_border_color               #f85525

active_tab_foreground           #00172e
active_tab_background           #faa968
inactive_tab_foreground         #3f8f8a
inactive_tab_background         #0a2640
tab_bar_background              #05182e

color0                          #00172e
color8                          #134e5a
color1                          #f85525
color9                          #f85525
color2                          #028391
color10                         #028391
color3                          #e97b3c
color11                         #e97b3c
color4                          #faa968
color12                         #faa968
color5                          #3f8f8a
color13                         #3f8f8a
color6                          #8cbfb8
color14                         #8cbfb8
color7                          #a7c9c6
color15                         #f6dcac
