## name: vantablack
## blurb: pure void black with clean monochrome accents

foreground                      #ffffff
background                      #0d0d0d
selection_foreground            #0d0d0d
selection_background            #ffffff

cursor                          #ffffff
cursor_text_color               #0d0d0d
url_color                       #b0b0b0

active_border_color             #8d8d8d
inactive_border_color           #1a1a1a
bell_border_color               #a4a4a4

active_tab_foreground           #0d0d0d
active_tab_background           #8d8d8d
inactive_tab_foreground         #3d3d3d
inactive_tab_background         #141414
tab_bar_background              #0d0d0d

color0                          #0d0d0d
color8                          #fdfdfd
color1                          #a4a4a4
color9                          #a4a4a4
color2                          #b6b6b6
color10                         #b6b6b6
color3                          #cecece
color11                         #cecece
color4                          #8d8d8d
color12                         #8d8d8d
color5                          #9b9b9b
color13                         #9b9b9b
color6                          #b0b0b0
color14                         #b0b0b0
color7                          #ececec
color15                         #ffffff
