# Auto-generated by theme-set.sh — do not edit directly
general {
    col.active_border = {{ hypr_active }}
    col.inactive_border = {{ hypr_inactive }}
}
decoration:shadow {
    color = {{ shadow_color }}
    color_inactive = {{ shadow_inactive }}
}
