# Auto-generated by theme-set.sh — do not edit directly
$c-time   = {{ accent2_rgba }}
$c-date   = {{ accent_rgba }}
$c-fg     = {{ foreground_rgba }}
$c-fg-dim = {{ foreground_dim_rgba }}
$c-accent = {{ accent_rgba }}
$c-field  = {{ background_field_rgba }}
$c-warn   = {{ urgent_rgba }}
