/* Auto-generated by theme-set.sh — do not edit directly */

* {
    bg:          {{ background }};
    bg-alt:      {{ bg_alt }};
    fg:          {{ foreground }};
    fg-alt:      {{ fg_alt }};
    accent:      {{ accent }};
    accent2:     {{ accent2 }};
    border:      {{ border }};
    urgent:      {{ urgent }};

    main-bg:     {{ background }};
    main-fg:     {{ foreground }};
    main-br:     {{ accent }};
    input-bg:    {{ bg_alt }};
    select-bg:   {{ accent }};
    select-fg:   {{ selection_fg }};

    background-color: transparent;
    text-color:       @fg;
}
