/* Auto-generated by theme-set.sh — do not edit directly */
@define-color main-bg    {{ background }};
@define-color main-fg    {{ foreground }};
@define-color accent     {{ accent }};
@define-color accent-bg  {{ bg_alt }};
@define-color hover      {{ bg_alt2 }};
@define-color active     {{ border }};
@define-color border     {{ accent }};
@define-color inactive-fg {{ fg_alt }};
