/* Auto-generated by theme-set.sh — do not edit directly */

@define-color main-fg         {{ foreground }};
@define-color main-bg         {{ background }};
@define-color main-br         {{ accent }};

@define-color active-bg       {{ accent }};
@define-color active-fg       {{ selection_fg }};

@define-color hover-bg        {{ border }};
@define-color hover-fg        {{ foreground }};

@define-color white           {{ foreground }};
@define-color black           {{ background }};

@define-color module-fg       {{ fg_alt }};
@define-color workspaces      {{ bg_alt }};

@define-color cpuinfo         {{ bg_alt }};
@define-color memory          {{ bg_alt2 }};
@define-color cpu             {{ bg_alt2 }};
@define-color distro-fg       {{ selection_fg }};
@define-color distro-bg       {{ accent }};
@define-color time            {{ bg_alt2 }};
@define-color date            {{ bg_alt }};
@define-color tray            {{ bg_alt }};

@define-color pulseaudio      {{ bg_alt }};
@define-color backlight       {{ bg_alt2 }};
@define-color battery         {{ bg_alt2 }};
@define-color power           {{ accent2 }};

@define-color good            {{ color2 }};
@define-color warning         {{ color3 }};
@define-color critical        {{ color1 }};
@define-color full            {{ accent2 }};
@define-color charging        {{ color2 }};
