source "$ONYX_INSTALL/packaging/helper.sh"

source "$ONYX_INSTALL/packaging/yay.sh"
source "$ONYX_INSTALL/packaging/hyprland.sh"
source "$ONYX_INSTALL/packaging/terminal.sh"
source "$ONYX_INSTALL/packaging/rofi.sh"
source "$ONYX_INSTALL/packaging/clipboard.sh"
source "$ONYX_INSTALL/packaging/waybar.sh"
source "$ONYX_INSTALL/packaging/notifications.sh"
source "$ONYX_INSTALL/packaging/audio.sh"
source "$ONYX_INSTALL/packaging/network.sh"
source "$ONYX_INSTALL/packaging/screenshot.sh"
source "$ONYX_INSTALL/packaging/brightness.sh"
source "$ONYX_INSTALL/packaging/system-tools.sh"
source "$ONYX_INSTALL/packaging/fonts.sh"
source "$ONYX_INSTALL/packaging/shell.sh"
source "$ONYX_INSTALL/packaging/sddm.sh"
