[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="ESPACION"
FontSize="13"

KeyboardSize="0.4"

RoundCorners="0"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d MMMM"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/sky_blue_bg.png"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.2"
DimBackgroundColor="#001428"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#caf0f8"
DateTextColor="#2d96b4"
TimeTextColor="#4bd2f0"

FormBackgroundColor="#001e3c"
BackgroundColor="#001428"
DimBackgroundColor="#001428"

LoginFieldBackgroundColor="#001428"
PasswordFieldBackgroundColor="#001428"
LoginFieldTextColor="#caf0f8"
PasswordFieldTextColor="#caf0f8"
UserIconColor="#2da5c3"
PasswordIconColor="#2da5c3"

PlaceholderTextColor="#0f5a78"
WarningColor="#e1b44b"

LoginButtonTextColor="#001428"
LoginButtonBackgroundColor="#2da5c3"
SystemButtonsIconsColor="#2d96b4"
SessionButtonTextColor="#2d96b4"
VirtualKeyboardButtonTextColor="#2d96b4"

DropdownTextColor="#caf0f8"
DropdownSelectedBackgroundColor="#2da5c3"
DropdownBackgroundColor="#001e3c"

HighlightTextColor="#001428"
HighlightBackgroundColor="#2da5c3"
HighlightBorderColor="#4bd2f0"

HoverUserIconColor="#4bd2f0"
HoverPasswordIconColor="#4bd2f0"
HoverSystemButtonsIconsColor="#4bd2f0"
HoverSessionButtonTextColor="#e1b44b"
HoverVirtualKeyboardButtonTextColor="#4bd2f0"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="48"
Blur="1.2"

HaveFormBackground="false"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="left"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
