general {
    lock_cmd         = pidof hyprlock || hyprlock          # avoid duplicate hyprlock
    before_sleep_cmd = loginctl lock-session               # lock before suspend
    after_sleep_cmd  = sleep 1 && hyprctl dispatch dpms on # turn on display after wake
    inhibit_sleep    = 3                                   # wait until screen is locked
}

# Stage 1 — 5 min: lock screen
listener {
    timeout    = 300
    on-timeout = pidof hyprlock || hyprlock
}

# Stage 2 — 5.5 min: turn off keyboard backlight
listener {
    timeout    = 330
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0
    on-resume  = brightnessctl -rd '*::kbd_backlight'
}

# Stage 3 — 5.5 min: turn off display
listener {
    timeout    = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on && brightnessctl -r
}

# Stage 4 — 20 min: suspend
listener {
    timeout    = 1200
    on-timeout = systemctl suspend
}
