################
### MONITORS ###
################
# https://wiki.hyprland.org/Configuring/Monitors/
# List available monitors: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

monitor=,preferred,auto,1

# For 4K / Retina screens — enable the next line and disable the previous:
# env = GDK_SCALE,2
# monitor=,preferred,auto,auto

# 1080p / 1440p screens — no change
# monitor=,preferred,auto,1

# Secondary monitor with 90° rotation:
# monitor = DP-2, preferred, auto, 1, transform, 1
